### PR TITLE
Add new GTNH EndGame Goal

### PR DESCRIPTION
**Pull request by LewisSaber**
Hello, dear Gregtech enthusiasts, ME and GDCloud worked very hard together to bring this new wonderful update to you!
In this update we extend our faivorite modpack GTNH to  new tier, Tier MAX
Here are recipes of new Components
image
image
image
image
image
image
image
image

We decided to integrate Botania into GTNH, since its a Tech mod after all, so most of those and next recipes will feature materials added by our beloved tech mod.
Together with that, all those components require new Material, MagMatter.
This mysterious material is very rare and its origin is beyond our understanding, but out best scientist managed to discover a way to manually recreate this beast of a material:
image
Since it requires so humongous temperatures to smelt, we developed a new and better Furnace
# Mega Volcanus
Everyone beloved furnace now get its older brother! Cant Believe Its finally Happening, this beast of multiblock will be able to fullfill any of your smelting requests with ease
image
image
image

With those new components you can now make new MAX tier energy hatches to boost your production even futher
image
image

Since we need Botania materials in great quantity now, we decided to make treader contract with elves, but those pesky dwarws refused, they said they have no use for UXV circuits we tried to give em.
# Humongous Eye of Harmony
With the help of one of our scientists we created a way to make those materials by extracting them directly from spacetime continuum.

image
image
image
image
https://github.com/GTNewHorizons/NewHorizonsCoreMod/assets/39595617/3a0a767e-c396-41a9-8498-7a98bdc5a374

# Stargate-11pro
With all those technologies we were able to finally make the best possible stargate, This Stargate-11pro more powerful than previous generations.
But such power comes at a cost(of your sanity)
image
image
image
image
image

# Endgame Goal
Unlocking Stargate-11pro full potential allows us to harness infinity directly
Meet the new endgame goal
The Infinite Power Generator
image

With this you can boost your production to unseen levels!

## Small Bonus
Small recipe change to balance recipe better
image
image

Thats all for today folk, We Hope you all enjoy this new balanced update

Credits
@LewisSaber - initiator
@GDCloudstrike - great guy, absolute Gigachad
@vovaksenov, @minecraft7771, @POPlol333 , @BlueWeabo  - some ideas

### CODE REVIEW

**Comment by boubou19** [comment]
Good work guys!

**Comment by vovaksenov** [comment]
I think the carefully selected values in the recipes show just how well balanced this update is! What a magnificent present to the GT:NH audience on the occasion of the upcoming 1.7.10's 10th anniversary!

**Comment by Cinobi** [comment]
Looking legit to me, approve

**Comment by NotAPenguin0** [comment]
LGTM!

**Review by chochem — APPROVED** [review]
thanks for the fix.

**Comment by Dream-Master** [comment]
:trollface:

**Comment by Nxer** [comment]
(6B$9HGJZ9FRN8UBPN`(`5K

**Comment by dragongod100** [comment]
I think these changes would be an excellent addition to the pack, it's been way too easy to speedrun stargates so having the Stargate-11pro added will give new challenges to speedruns!

**Comment by Kyium** [comment]
What about the stargate 11-pro max? Looks too easy otherwise. Great additions though, especially my favorite tech mod botania getting its much needed important integration!

**Pull request merged**
