### PR TITLE
Add Glue Balls to Board recipes

### PR DESCRIPTION
**Pull request by Dream-Master**
* Use Glue Balls instead of sticky risin when make Basic Circuit boards
* Add control circuits to all assembler recipes
* Add Circuit part recipes with slime balls/glue

### CODE REVIEW

**Comment by Prometheus0000** [comment]
Will people actually use this though? Getting glue from the smeltery is a huge pain after all.

**Comment by Dream-Master** [comment]
Yea maybe i need to think off an alternative but i dont like it be only sticky resin. Maybe rubber dust ?

**Comment by Prometheus0000** [comment]
What about adding an oredicted version of slimeballs (might be a different oredict, I can't see it on the stripped pack I have)? Like the recipe for magma cream. That would mean glue, slime balls of both types, blood drops all would be usable.

You also need to keep in mind that after you get the assembler you're just going to skip making coated boards and make circuit boards directly. So making it too advanced (I thought of adding an assembler GT glue recipe) won't work out either.

**Comment by Dream-Master** [comment]
> What about adding an oredicted version of slimeballs (might be a different oredict, I can't see it on the stripped pack I have)? Like the recipe for magma cream. That would mean glue, slime balls of both types, blood drops all would be usable.
> 
> You also need to keep in mind that after you get the assembler you're just going to skip making coated boards and make circuit boards directly. So making it too advanced (I thought of adding an assembler GT glue recipe) won't work out either.

Yes the slimeball idea ordict comes in my mind but i dont find any existing one. Maybe i need to create one.
Sure it is only before assembler. I am atm in this situation. Have a bender working on a Lathe and after this assembler.

**Comment by Dream-Master** [comment]
@Prometheus0000 add more recipe variants

**Comment by Prometheus0000** [comment]
OK

**Comment by Dream-Master** [comment]
image
image

**Pull request merged**
