### PR TITLE
More readable recipes.

### PR DESCRIPTION
**Pull request by kuba6000**
Not 100% done

### CODE REVIEW

**Comment by chochem** [comment]
you mentioned you can easily regenerate this one right?

**Comment by kuba6000** [comment]
> you mentioned you can easily regenerate this one right?

Yes. I will reset to master and regenetate the changes with my script tomorrow. Currently going to sleep.

**Review by Connor-Colenso — APPROVED** [review]
Realistically I don't see this getting a proper review. We will know if some important stuff is gone from user feedback.

**Comment by Dream-Master** [comment]
thanks. So i don't need to log in to see what meta id is meant

**Pull request merged**
