### PR TITLE
Add new recipes to star fuel and dark matter

### PR DESCRIPTION
**Pull request by GDCloudstrike**
This PR adds a new recipes to the avaritia star fuel item and amun ra dark matter, both of which are planned to be used in the upcoming godforge multiblock. Dark matter can be found naturally generating on the mehen belt, these recipes are optional ones for those who dont want to go search for it in world.
image
image
image

### CODE REVIEW

**Review by NotAPenguin0 — APPROVED** [review]
Using mk5 naqfuel in the recipe is evil, I like it.

**Comment by Reflex18** [comment]
> Using mk5 naqfuel in the recipe is evil, I like it.

Doesnt that basically enforce one power type over the other?

**Comment by NotAPenguin0** [comment]
> Doesnt that basically enforce one power type over the other?

It's only used for crafting, so not really.

**Comment by Persus1** [comment]
I dont know how much Dark Matter you will need, but i do remember that you could use Fortune on the Dark Matter blocks. With this you could get over a stack of Dark Matter with the World Breaker(or more if you create even higher Fortune Levels). So if you dont search on Mehen Belt for the really rare meteor you probably just need to do this recipe one time.

Just thought about this while seeing the Extractor recipe for just 8 pieces.

**Pull request merged**
