### PR TITLE
Add Apiamancer's Drainer recipe

### PR DESCRIPTION
**Pull request by Quantumlyy**
image
image

### CODE REVIEW

**Comment by Dream-Master** [comment]
Need this https://github.com/GTNewHorizons/MagicBees/pull/34

**Comment by Alastors** [comment]
Reduce the tempus to 25 IMO, it's a rare spawn that literally only generates on golden clocks from vanilla

**Comment by Quantumlyy** [comment]
> Reduce the tempus to 25 IMO, it's a rare spawn that literally only generates on golden clocks from vanilla
> 
> Otherwise the rest of the recipe is fine, though I'd alter the order for aesthetics, I.e. lower the right pollen by 1 (switching it with a log) and raise the left pollen by 1

50 Tempus isn't that bad seeing as how each clock has 4. So ~13 clocks seems not terrible.

**Comment by Dream-Master** [comment]
> > Reduce the tempus to 25 IMO, it's a rare spawn that literally only generates on golden clocks from vanilla
> > Otherwise the rest of the recipe is fine, though I'd alter the order for aesthetics, I.e. lower the right pollen by 1 (switching it with a log) and raise the left pollen by 1
> 
> 50 Tempus isn't that bad seeing as how each clock has 4. So ~13 clocks seems not terrible.

i changed it back but keep symmetry in recipe i changed before

**Review by Dream-Master — APPROVED** [review]

**Comment by Alastors** [comment]
We need to revisit this, this block was never meant to be IV

**Comment by Dream-Master** [comment]
@Alastors there are also bugs with the block. I try to reach Quantumly but he not answering.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15510

**Pull request merged**
