### PR TITLE
Asmd rework

### PR DESCRIPTION
**Pull request by Dream-Master**

### CODE REVIEW

**Comment by Sphyix** [comment]
Looks fine for me

**Comment by Glease** [comment]
Then tungsten smelting time needs tweaking. The old value is made based on the assumption that *you only need so many pure tungsten until all you need is tungstensteel*. Just adding lots of tungsten into the mix is a strict nerf.

**Review by Glease — COMMENTED** [review]
Looks fine by me. (IV end, assline done) Not sure what those end game player think.

**Comment by Sphyix** [comment]
Makes more sense to use tungstensteel,  I wasn't thinking at the smelt time, so good change.
Idk, I liked the recipes how they were initially on 2.1.1.0, but if a nerf is needed this looks fine.

**Review by GTNH-Colen — APPROVED** [review]

**Comment by Dream-Master** [comment]
xsmd will follow later after the update

**Pull request merged**
