### PR TITLE
fix LUV-UEV Scanner recipes

### PR DESCRIPTION
**Pull request by MotiasF33**
issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6630

### CODE REVIEW

**Comment by Prometheus0000** [comment]
Can you stop putting fix before the number, it closes the issue after merging. https://docs.github.com/en/enterprise/2.13/user/articles/closing-issues-using-keywords#:~:text=You%20can%20include%20keywords%20in,pull%20request%20and%20the%20issue.

**Comment by MotiasF33** [comment]
> 
> 
> Can you stop putting fix before the number, it closes the issue after merging. https://docs.github.com/en/enterprise/2.13/user/articles/closing-issues-using-keywords#:~:text=You%20can%20include%20keywords%20in,pull%20request%20and%20the%20issue.

sry I did not know 😽

**Comment by Dream-Master** [comment]
can this merged ? @Prometheus0000 @MotiasF33

**Comment by MotiasF33** [comment]
> 
> 
> can this merged ? @Prometheus0000 @MotiasF33

my yes

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
