### PR TITLE
update tank capacity on GT machines in coremod

### PR DESCRIPTION
**Pull request by Pxx500**
second part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/1999

### CODE REVIEW

**Comment by Dream-Master** [comment]
Why 128 is max. Did I miss a vote or a suggestion about this value ?

**Comment by Pxx500** [comment]
> Why 128 buckets is max. Did I miss a vote or a suggestion about this value ?

Anything higher than 128 makes no sense since most of the fluid will be idling inside the tank and not buffering since pretty much no recipes use more than a few buckets anymore after chemical rebalance. Also all machines in coremod are high-tier and most will be used in PA anyway so fluid tank capacity is irrelevant for the most part. I used 128 because it seems like a good compromise between being low enough to not seem weird and high enough to not cause buffering problems.

**Comment by Dream-Master** [comment]
ok fair enough but then the gt pr is wrong. it set a default to 64 not 128. Andy why you not use the code from gt instead of type in the values?

**Comment by Pxx500** [comment]
> ok fair enough but then the gt pr is wrong. it set a default to 64 not 128. Andy why you not use the code from gt instead of type in the values?

Not that i think about it 256 is also very convenient since drums have this value. Maybe we'll go with that?

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
