### PR TITLE
Add 9x ghast tear saltwater recipe

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7602

### CODE REVIEW

**Review by Ethryan — APPROVED** [review]
I approve of this, It would make the clorine setup easier and not spawn so many tiny dusts.

**Comment by Dream-Master** [comment]
But why a ghast tear recipe ?

**Comment by Glease** [comment]
Renewable source of salt water (and hence chlorine, sodium and its compounds) instead of pumping it from space. Ghast tear comes from either tearstalk (ic2 crop) or a real ghast farm.

**Comment by Prometheus0000** [comment]
> But why a ghast tear recipe ?

Read the linked issue.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
