### PR TITLE
added 1 and 8 EU solar panels to the assembler

### PR DESCRIPTION
**Pull request by boubou19**
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9405
image
image

### CODE REVIEW

**Comment by bombcar** [comment]
Same tier and energy for both?

**Comment by boubou19** [comment]
assembler recipes are sometime weird. I just based the recipe power consumption and time on this recipe:
image

**Comment by bombcar** [comment]
Sounds good just wanted to make sure we weren’t accidentally gating something

kinda like “low power at tier” recipes Iike 16v 64v 256v heh

**Comment by bombcar** [comment]
Making it easy to read instead of one huge line what is this even!

**Review by bombcar — APPROVED** [review]

**Comment by boubou19** [comment]
yeah, i'm sick of those long ass lines, so when i touch something, i make it easy to read 😎

**Pull request merged**
