### PR TITLE
Set hardness of the Ztones glass to be the same as normal glass

### PR DESCRIPTION
**Pull request by Alexdoru**
Currently the Ztones glass is insta break which makes it annoying to work with since you will constantly break some of it accidentally. Since it is insta break it will also often create ghost blocks. This pr sets the hardness of the block to be the same as vanilla glass.

### CODE REVIEW

**Review by OneEyeMaker — APPROVED** [review]

**Comment by S4mpsa** [comment]
I hate this.

**Comment by Ultraxite** [comment]
more than anything in the world i want this reverted, having instant breaking glass with punch is exceptionally useful.

**Comment by Dream-Master** [comment]
@S4mpsa which hardness you suggest ?

**Comment by boubou19** [comment]
with a vajra there is no diff. idk why it's an issue?

**Comment by S4mpsa** [comment]
It means you now need to switch to a Vajra when you do a mistake. Just a minor annoyance, but I suppose it is subjective seeing as Alexdoru sees it the other way around.

**Comment by Ultraxite** [comment]
@boubou19 @Dream-Master being able to instant break it with just fists was very convenient. 

vajra is annoying to use especially for endgame when theres a lot of lag because u tend to break more than you intend when u left click with vajra. tinted glass breaking with fists meant you can hold down left click and only break glass and no other blocks.

**Pull request merged**
