### PR TITLE
Fix broken tinkers defence recipes

### PR DESCRIPTION
**Pull request by chochem**
fix incorrect item names in 5 tinkers defence recipes.

fixes the last few point and thus closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15676

image
image

### CODE REVIEW

**Review by Ethryan — APPROVED** [review]
Huh, Strange naming scheme for the item ids...

**Comment by chochem** [comment]
yea a bit strange for sure. I just used `/mt hand' and copied that in. :P

**Comment by Dream-Master** [comment]
Use /iih         ingame is more  accurate . You get much more infos.

**Comment by chochem** [comment]
its not more accurate. its the same thing on that front. and it doesnt copy.

**Pull request merged**
