### PR TITLE
Recipe for Portable Shower

### PR DESCRIPTION
**Pull request by OmdaCZ**
Part 2 of https://github.com/GTNewHorizons/WarpTheory/pull/42 , my suggestion for the recipe is in the following picture.

image
15x Ichorium Fine Wire
15x Ichorium Foil
3x Tiny Neutronium Pipe
1x Arcane Spa
1x XP Shower
1x Sprinkler
1x UV pump
1x UV conveyor
1x Quantum Chest IV
1x Reservoir Hatch

### CODE REVIEW

**Comment by Dream-Master** [comment]
@OmdaCZ the icon looks a bit wired maybe we can ask the graphic devs to improve this a bit?

**Comment by OmdaCZ** [comment]
Yes of course, I even mentioned the icon being WiP in my first PR.

**Comment by Dream-Master** [comment]
> Yes of course, I even mentioned the icon being WiP in my first PR.

this was no complain only and idea to exchange it maybe

**Comment by Dream-Master** [comment]
i just wait for a better texture before merge

**Comment by OmdaCZ** [comment]
image
this is my updated suggestion, added some Ichorcloth as requested

**Comment by FourIsTheNumber** [comment]
I still think this should be a magic recipe, probably infusion altar with research

**Comment by Dream-Master** [comment]
> I still think this should be a magic recipe, probably infusion altar with research

you cant put so much recipe ingredients on it i guess. Some day i want Avatia table recipe act like Fusion 2.0 . Use essentia have some mix out of crafting 9x9 recipe and magic

**Comment by OmdaCZ** [comment]
I don't think that infusion has any hard cap on item number in recipe

**Comment by Dream-Master** [comment]
@OmdaCZ ok do a infusion recipe. ingredients are ok i think. Check about the essntia that it is more expensive than the pure amulet

**Comment by Dream-Master** [comment]
@OmdaCZ can you show me the recipe here ?

**Comment by Dream-Master** [comment]
It’s looks much cheaper than the 9x9 I would say.

**Comment by OmdaCZ** [comment]
The overall Ichorium cost is way higher in this case, also requires HIP module compressor and some trip to getting the Aequalitas and Gloria essentia, but yes it should be ZPM now instead of UV components.

**Comment by Ethryan** [comment]
Isn't Instability capped at 25 and if you try and go over that it causes some problems?

**Comment by OmdaCZ** [comment]
Shards of Laputa already exceed that by a lot and I dont remember anyone mentioning any problem with them

**Review by Dream-Master — APPROVED** [review]

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
