### PR TITLE
Add lapotronic energy orb cluster space assembler recipe

### PR DESCRIPTION
**Pull request by GDCloudstrike**
Adds a space assembler recipe for lapotronic energy orb clusters to keep it consistent with the other energy orbs and to make faster than 1 tick production of these possible.

image

### CODE REVIEW

**Comment by miaowwwwww** [comment]
good stuff

**Comment by Pelotrio** [comment]
I am definitely a fan of adding a recipe for this in the space assembler but I dont think its a good idea to just use the assembly line recipe for it. This is not consistent with the other recipes for energy cluster which all are a bit cheaper but require more high level material. Due to the usages of the energy orb cluster in higher tier recipes I would recommend to change the recipe to be consistent with the other cluster types.

**Comment by GDCloudstrike** [comment]
> I am definitely a fan of adding a recipe for this in the space assembler but I dont think its a good idea to just use the assembly line recipe for it. This is not consistent with the other recipes for energy cluster which all are a bit cheaper but require more high level material. Due to the usages of the energy orb cluster in higher tier recipes I would recommend to change the recipe to be consistent with the other cluster types.

the reason I decided to not make this recipe cheaper is because this already _is_ the cheaper recipe that uses less higher tier materials. 
If you look at the recipe structure, the cheaper higher tier clusters are based on this recipe, so they are inherently consistent because their basic structure aligns with this recipe.

**Review by BlueWeabo — APPROVED** [review]
Thanks for your work

**Comment by Dream-Master** [comment]
@Pelotrio feel free to add a new recipe or change the existing ones.

**Comment by Pelotrio** [comment]
> > I am definitely a fan of adding a recipe for this in the space assembler but I dont think its a good idea to just use the assembly line recipe for it. This is not consistent with the other recipes for energy cluster which all are a bit cheaper but require more high level material. Due to the usages of the energy orb cluster in higher tier recipes I would recommend to change the recipe to be consistent with the other cluster types.
> 
> the reason I decided to not make this recipe cheaper is because this already _is_ the cheaper recipe that uses less higher tier materials. 
> If you look at the recipe structure, the cheaper higher tier clusters are based on this recipe, so they are inherently consistent because their basic structure aligns with this recipe.

These are valid points but I am still not sure if it should be completely identical. Also does the assembler oc the recipe? What about making it a recipe with more Inputs and more outpus eg. 4

**Comment by Dream-Master** [comment]
i am not sure if the item is stackable?

**Pull request merged**
