### PR TITLE
Retster Tier down 4 Opencomputers recipe from HV to MV

### PR DESCRIPTION
**Pull request by Retster**
Minor fix to yesturday PR:
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/282

Changed:
microchip tier 2 to microchip tier 1 in recipes of:

Inventory controller upgrade
Tank controller upgrade 
Generator upgrade 
Crafting upgrade 

in case it was still HV craft(because microchip tier 2 is HV) but should be MV
this issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9528

### CODE REVIEW

**Comment by repo-alt** [comment]
Because the previous PR was already merged, there are conflicts now, so please rebase your branch on current `master`

**Comment by Retster** [comment]
> Because the previous PR was already merged, there are conflicts now, so please rebase your branch on current `master`

Now i understand, will try to fix. Thank you for review!

**Comment by Dream-Master** [comment]
@Retster done.
Why change stuff to mv? What is the reson for it ?

**Comment by Retster** [comment]
> @Retster done. Why change stuff to mv? What is the reson for it ?
This changes is give to players alternatywe of boring hand crafting and just rushing to EV+ where is Applied energistics is exist. 
And make posible to make real automation start in MV if you put some effort in playing with Opencomputers. 

also partially explanation in this issue:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9528

ps: now i trying to fight with git rebase to make PR properly, but if you think that this is bad changes then i give up

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
