### PR TITLE
Add Amun-Ra Recipes

### PR DESCRIPTION
**Pull request by glowredman**
Feedback is highly appreciated, as I have no idea how to properly balance in UHV. The goal is that the Mothership can be built at the end of UHV and should be as high of a gate as the rockets.

### Mandatory Mothership related recipes
*Mothership*
grafik
*Mothership Navigation Console*
grafik
grafik
*Rocket Engine Jet*
grafik
grafik
*Rocket Engine Base*
grafik
grafik
*Nanite Cluster*
grafik
grafik
*Nanite Control Module*
grafik
### Additional Mothership related recipes
*Mothership Configuration Terminal*
grafik
*Ion Thruster Jet*
grafik
grafik
*Shuttle Dock*
grafik
*Ion Thruster Base*
grafik
grafik
*Dock Gangway*
grafik
*Dock Door*
grafik
### Shuttle recipes
*Shuttle Legs*
grafik
grafik
*Lightweight Alloy Ingot*
grafik
grafik
*Ligthtweight Plate*
grafik
grafik
*Shuttle Nose Cone*
grafik
grafik
*Shuttle Schematic*
grafik
grafik
*Shuttle Rocket*
Note: the three green slots can be filled with either a Copper Chest or Copper tank to provide cargo space.
Note: this recipe is defined in the Amun-Ra code itself.
grafik
### Other recipes
*Basalt*
grafik
*Red Sandstone*
grafik
*Olivine Bsalt*
grafik
*Aluminum Box*
grafik
*Planks*
Analogous recipe for Lumipod Planks
grafik
grafik
grafik
grafik
grafik
*Basalt Brick*
grafik
*Smooth Basalt*
grafik
*Obsidian Brick*
grafik
*Crafting Table*
grafik
*Block Scale*
grafik
*Artificial Gravity Generator*
grafik
*Hydroponics Unit*
grafik
*Stairs*
Analogous recipe for Smooth Basalt, Basalt Brick, Basalt, Aluminium Box, Virilig Planks and Lumipod Planks
grafik
*Slab*
Analogous recipe for Smooth Basalt, Basalt Brick, Basalt, Aluminium Box, Virilig Planks and Lumipod Planks
grafik
grafik
grafik
grafik
*Artificial Gravity Disruptor*
grafik

### CODE REVIEW

**Comment by King65868** [comment]
Just a few things I noticed:
If this is supposed to be late UHV I see a UIV assembly line recipe that couldn’t be done then. Also is that purple tape in the Ion Thruster Jet and a few others the Hyper-Stable Self-Healing Adhesive? If so that’s UEV gated by the quantum force transformer.

**Comment by chochem** [comment]
early uev and a uiv assembly line would be appropriate if this is a T9 rocket

**Comment by TheEpicGamer274** [comment]
this rocket is the gate to uev so that has to be changed

**Comment by chochem** [comment]
ah right, you cant make uev energy hatches without it :P

**Comment by glowredman** [comment]
> Just a few things I noticed: If this is supposed to be late UHV I see a UIV assembly line recipe that couldn’t be done then. Also is that purple tape in the Ion Thruster Jet and a few others the Hyper-Stable Self-Healing Adhesive? If so that’s UEV gated by the quantum force transformer.

The Heavy Duty Alloy Ingots always seem to have a tier + 2 recipe (T8 -> UEV, T7 -> UHV, ...), so I just continued this trend.
Yes, that tape is Hyper-Stable Self-Healing Adhesive. I did not notice it being QFT-locked, I need to substitute a different item then.

Also, as a note: The minimum requirement to access T9 would be
- 1 Shuttle Rocket
- 1 Mothership
- 3 Rocket Engine Base
- 1 Rocket Engine Jet

**Comment by Dream-Master** [comment]
beside maybe some minor changes i think we can merge this now.

**Comment by Dream-Master** [comment]
if we need more changes we can do it in a seperated pr.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
