### PR TITLE
Fixed recipes containing GT arrows to use Thaumcraft elemental ones instead

### PR DESCRIPTION
**Pull request by dagger8243**
**Fixed Recipes:**
- Robes of the Stratosphere
- Wand Focus: Explosion
- Wand Focus: Shadowbeam
image
image
image

### CODE REVIEW

**Review by chochem — DISMISSED** [review]
looks good

**Comment by Dream-Master** [comment]
Is the orange ingot ichorium ? Are we have plates ? Sure it’s just a visual thing but for the armor plate loocks nicer . About the wand core idk

**Comment by EnderProyects** [comment]
Yea, now that we are changing the recipes it could also change the ichorium

**Review by Dream-Master — CHANGES_REQUESTED** [review]
change it to plates/rings/foils etc. Not use ingots

**Comment by dagger8243** [comment]
i will never ever use idea git implementation ever again, god that made a mess sorry,

anyways i updated the robes to use plates and shadowbeam focus to use ring, this good ?
image
image

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
