### PR TITLE
Fix classloading order when not all mods are loaded

### PR DESCRIPTION
**Pull request by Glease**
Fixes GTNewHorizons/GT-New-Horizons-Modpack#7515

### CODE REVIEW

**Comment by bartimaeusnek** [comment]
wat?

**Comment by Dream-Master** [comment]
?

**Comment by repo-alt** [comment]
it requires a Java dev to understand that

**Comment by bartimaeusnek** [comment]
I guess, this encapusulates the GT_Block_CasingsNH class, so it doesnt get loaded during initialisation of the mod container. still a bit weird for a fix. Maybe we should move the ModContainer as a whole, or create a Pipeline (which Forge already offers) to prevent such weird breakages in the future.

**Comment by Glease** [comment]
Somehow the verifier fires before the method is called. This ensures the verifier doesn't see classes not yet present on classpath.

**Review by repo-alt — APPROVED** [review]
This is a piece of black magic, but if it works, ok.

**Pull request merged**
