### PR TITLE
fix disassemble dupe

### PR DESCRIPTION
**Pull request by GlodBlock**
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8426

### CODE REVIEW

**Comment by Prometheus0000** [comment]
So you just made them not disassemble-able? I don't think that's a proper solution.

**Comment by GlodBlock** [comment]
no, i only make the crafting table recipe can be disassembled. it is still disassembleable for its assemble recipe.
图片

**Comment by Dream-Master** [comment]
i guess there houndet of recipes have this tag. Not sure if we should remove this tag from whole gtu5 ?

**Comment by GlodBlock** [comment]
not necessary. if all of these tags are removed, the disassembler won't be able to disassemble any matchines or something that doesn't have a assemble recipe.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
