### PR TITLE
Wireless data recipes

### PR DESCRIPTION
**Pull request by NotAPenguin0**
All recipes tiered at UMV.

image
image

image
image

### CODE REVIEW

**Comment by EnderProyects** [comment]
Just saying but for parity shouldnt all crafts use the internet card?

**Comment by NotAPenguin0** [comment]
Yeah this makes sense honestly, I don't really know why I didn't make the data stick ones use it

**Comment by EnderProyects** [comment]
I mean in the description all are internet conected xd

**Review by S4mpsa — APPROVED** [review]
Tested in full pack and everything looks as expected.

One problem for the future might be the explicit usage of the Quantum circuit, if other UXV circuits are ever added. But this should be fixed by adding oreDict to the Quantum circuit at that point.

**Pull request merged**
