### PR TITLE
Added research and recipe for Crimson Rites Book and Crimson Cult Banner

### PR DESCRIPTION
**Pull request by Dyonovan**
All recipes are based on the conversation @ https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14860

Researched is located on the Eldritch tab locked behind ELDRICHMAJOR (Eldrich Revelation). The banner recipe doesn't appear in the Thaumonomicon as there is no way to not compare by NBT so it only picks up the first recipe of the basic Thaumcraft banner. Recipe does show up in NEI.

### CODE REVIEW

**Comment by Dyonovan** [comment]
Just realized it picked up my latest pull request. Didnt realize it did that. Do you want me to remove it?

**Comment by Dream-Master** [comment]
> Just realized it picked up my latest push. Didnt realize it did that. Do you want me to remove it?

what you mean ?

**Comment by Dyonovan** [comment]
Yea thats it. I was going to add a pull request eventually so if its ok just leave it in?

**Comment by chochem** [comment]
no. dont put unrelated stuff in.

why would we want a recipe for broken spawner anyway. that would reduce exploration even more.

**Comment by Dream-Master** [comment]
@Dyonovan revert it and put it in a second pr. this have nothing todo with the first change.

**Comment by Dyonovan** [comment]
I have removed that commit

**Comment by Dream-Master** [comment]
this commit had parts of the crimson rites pr guess you need re add it ? @Dyonovan

**Comment by Dyonovan** [comment]
Yes. Doing it right now. just testing it

**Comment by Dyonovan** [comment]
And Done.

**Review by combusterf — APPROVED** [review]
Looks fine to me, merge if peaceful mode support is desired.

**Comment by Dream-Master** [comment]
@Dyonovan

**Comment by Dyonovan** [comment]
I actually didn't do it for the peaceful run crowd, but for the sky block crowd. It's gated fairly high up the thaumcraft tree to be nice to have for all, but most people will be past that stage when it unlocks

**Pull request merged**
