### PR TITLE
Restore (accidentally?) removed ProjectRed recipes.

### PR DESCRIPTION
**Pull request by AbdielKavash**
In https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/840, Project Red Transportation has been downtiered and many recipes changed. However, in this PR, recipes for several PR parts have been completely removed: Silicon, Red Silicon Compound, Infused Silicon, and Silicon Chip. These recipes make up a crafting chain, and the Silicon Chip is used to craft several PR logic gates, which are unobtainable otherwise. This PR restores the four removed recipes.

We talked about this with @chochem on discord, and I believe this removal was accidental, as I see no reason for it. I suspect @Dream-Master simply did not notice that the chips have other uses than logistic pipes and thought them redundant. If there is any legitimate reason to remove these recipes, then an alternate way of crafting the affected gates should be added instead.

### CODE REVIEW

**Review by chochem — DISMISSED** [review]
looks good.

One use was removed (on purpose). So yea, dream probably didnt realize they have other uses.

**Comment by Dream-Master** [comment]
I will check tomorrow . Please not merge yet. I was thinking to use gt silicon boule / silicon chips from gt instead when i change recipes but bouls are late lv. And maybe a engraver to get different colors . (Yes I not realized they used elsewhere )

**Comment by AbdielKavash** [comment]
Sounds good, we already suggested some alternate recipes. I don't mind, as long as the gates are craftable again <3

**Comment by Dream-Master** [comment]
image
image
image
image
image
image
image
image
image

**Review by OrderedSet86 — APPROVED** [review]
Looks good to me

**Pull request merged**
