### PR TITLE
make lever assembler recipe cheaper

### PR DESCRIPTION
**Pull request by Glease**
We encourage automation, not desuade it. Pressure plate -> button -> lever is a tediusly long chain and it's not justified for a simple item such as lever.

### CODE REVIEW

**Comment by chochem** [comment]
why are you ungregifying stuff? I dont see any reason.

**Comment by Glease** [comment]
Pressure plate -> button -> lever is a tediusly long chain and it's not justified for a simple item such as lever.

**Comment by chochem** [comment]
this is GTNH xD

**Comment by Glease** [comment]
I don't want to get rude here but I'm just gonna get a freaking LEVER from NEI

The original GT5 recipe is just stick+cobble in assembler. I even added some redstone

**Comment by HoleFish** [comment]
Make stone button cheaper

**Comment by chochem** [comment]
> I don't want to get rude here but I'm just gonna get a freaking LEVER from NEI
> 
> The original GT5 recipe is just stick+cobble in assembler. I even added some redstone

I guess dreamified is more accurate than gregified :P

**Review by Dream-Master — CHANGES_REQUESTED** [review]
But stone looks very ugly . Will check if I can make another recipe in this row cheaper maybe the machine one .

**Comment by Glease** [comment]
Screw your balance. I'm done with this business.

**Comment by Dream-Master** [comment]
? Why so angry ? I have already a better idea but I am not at home and will take care later.

**Comment by Glease** [comment]
Yeah sure. Do it in your own PR then.

**Pull request closed without merging**
