### PR TITLE
Add LCR AssemblerRecipes.

### PR DESCRIPTION
**Pull request by DarkAhri**
Add LCR AssemblerRecipes.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@DarkAhri thanks for your pr but can you explain what recipe you add?

**Comment by Dream-Master** [comment]
your build fail. can you run spotless?

**Comment by DarkAhri** [comment]
> @DarkAhri thanks for your pr but can you explain what recipe you add?

Adds assembler recipes to the LCR controller blocks.

**Comment by chochem** [comment]
as there is no circuit, did you check for conflicts?

**Comment by DarkAhri** [comment]
> as there is no circuit, did you check for conflicts?

there's no confilct, but  adding circuit is a good idea.

**Comment by Dream-Master** [comment]
@DarkAhri are you add the circuit to the recipe ?

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
