### PR TITLE
Fix baklava giving fire resistance

### PR DESCRIPTION
**Pull request by Elisis**
See: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7359

### CODE REVIEW

**Comment by bartimaeusnek** [comment]
How about we just do this instead of this whole "detection" function? Should be sufficient...

```JAVA
ItemData assoc = GT_OreDictUnificator.getAssociation(pHeldItem);
if (assoc == null || assoc.Material == null || assoc.Material.Material != Materials.Lava)
    return false;
return true;
```

**Comment by Dream-Master** [comment]
@Elisis

**Comment by Elisis** [comment]
Yeah, I'll change it when I can.

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by bartimaeusnek** [comment]
Needs to be tested. Since I don't have any idea if it will really work out in-game.

**Comment by Dream-Master** [comment]
I merge this now so we can test it on zeta later

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
