### PR TITLE
Add remaining IronChest Assembler options

### PR DESCRIPTION
**Pull request by BritishCynic**
Provides more comprehensive options for https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11226.

Adds new options for constructing Steel, Iron, Gold and Diamond Chests by allowing previous chests to be used with their existing upgrade materials from the manual upgrades.

### CODE REVIEW

**Comment by BritishCynic** [comment]
Error from the build bot:

fatal: unable to access 'https://github.com/GTNewHorizons/NewHorizonsCoreMod/': The requested URL returned error: 403

**Comment by Dream-Master** [comment]
@BritishCynic can you run spotless apply

**Comment by BritishCynic** [comment]
Still returning a 403 error, that's a HTTP Forbidden error

**Comment by glowredman** [comment]
Run gradlew updateBS

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
