### PR TITLE
add stargateController recipe

### PR DESCRIPTION
**Pull request by wohaopa**
I want to add a recipe for this block, but I'm not sure if it's appropriate.
https://github.com/GTNewHorizons/SGCraft/pull/19

### CODE REVIEW

**Review by NotAPenguin0 — DISMISSED** [review]
While appreciated, I think this should be a part of https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/980 instead of going in a separate PR.

**Comment by wohaopa** [comment]
> While appreciated, I think this should be a part of #980 instead of going in a separate PR.

I agree. What should I do?

**Comment by Dream-Master** [comment]
@wohaopa all fine you already add it to this branch.

**Comment by NotAPenguin0** [comment]
This is fine, I didn't see the PR was going into the 2.7-stargate branch instead of master

**Review by serenibyss — APPROVED** [review]
Thanks for this! I love the idea. We will probably tweak the recipe some, but I'll merge it into the Stargate PR in the meantime

**Pull request merged**
