### PR TITLE
Add a few missing assembler recipes for large-volume items.

### PR DESCRIPTION
**Pull request by NotAPenguin0**
This PR adds assembler recipes for a few items that are used in large volumes.

AE2 related stuff:
- AE2 basic and advanced card
- Advanced blocking card
- Pattern capacity card
- Acceleration card
- Hyper-Acceleration card
- Flat ME interface (this uses the same recipe as a regular interface but with a different circuit number, as suggested in GTNewHorizons/GT-New-Horizons-Modpack#15276)

DTPF casings:
- Super Chest V
- Super Tank V
- IV Chest Buffer
- UV Microwave Transmitter

Yottank cells/EOH parts
- UV compressor

Dyson related stuff (by @C0bra5)
- IC2 Advanced Machine Casing
- IC2 Stirling Generator
- IC2 Heat Component

Various
- EV bending machine (used by bending machine multi) by @C0bra5

### CODE REVIEW

**Comment by chochem** [comment]
the lack of programmed circuits might be an issue. how well did you check for conflicts?

**Comment by NotAPenguin0** [comment]
Not well, I need to take a better look at this first probably, only really checked the interface one but that does have a circuit.

**Comment by NotAPenguin0** [comment]
Fixed one issue, and gave all ae2 cards circuit #2, since most other ae2 parts seem to have that circuit number as well. Also had a look through all recipes and couldn't find any conflicts.

**Comment by C0bra5** [comment]
Here are the recipes for the ic2 stuff needed to craft Dyson modules:
image
image
image
image

You can adjust the craft times or EU costs, I just took values from somewhat similar items.

**Pull request merged**
