### PR TITLE
Fix obsidian stick conversion recipes

### PR DESCRIPTION
**Pull request by chochem**
They are conflicting and which one you actually get seems to depend on version/restart/or something.

I made them shapedore recipes instead. topleft you get the tinker version, topmiddle randomthings, topright GT. Any works as input.

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10011.

image

edit: uh something still isnt right. draft until I fix it (or someone else). Right now the first 2 are working but I also get the tinker variant topright even though it shows gt in nei. :( Looks like the recipe conflict was just one of the problems here.
edit2:restart and now its wrong the otherway around. topmiddle and topright are correct but topleft gives GT. uff. will try to understand on the weekend.

### CODE REVIEW

**Comment by EnderProyects** [comment]
Why you dont make a recipe that cycles the 3 recipes instead of making a place one?

**Comment by chochem** [comment]
I dont see how that is relevant. seems better this way.

**Comment by EnderProyects** [comment]
Because it will not cause conflicts

**Comment by chochem** [comment]
alright kuba and boubou quickly helped. problem was that it's not position but really a 'shape'. here are the new ones, all working now:
image

**Pull request merged**
