### PR TITLE
Mica based plate

### PR DESCRIPTION
**Pull request by Dream-Master**
recipe use a plate mold now

### CODE REVIEW

**Review by chochem — CHANGES_REQUESTED** [review]
this doesn't work. the LV and MV forming press only have 2 input slots. (HV is 4)
but we need this in LV.

**Comment by Dream-Master** [comment]
ok this wont work at lv maybe i add it at hv to get a better ratio

**Comment by chochem** [comment]
now there is only the HV one.
If you want both you would also need to make sure they arent conflicting with each other.

**Comment by Dream-Master** [comment]
yea i add it back.

**Comment by Dream-Master** [comment]
i coul add a control circuit for hv one because it has 4 slots

**Comment by chochem** [comment]
they still conflict. The HV one was not the problem, it has the form. but the LV one has nothing to separate it.

**Comment by chochem** [comment]
in fact I just quickly loaded the latest changes here. And in-game only the LV one shows up due to the conflict.

**Comment by Dream-Master** [comment]
i will check ingame if it show a conflict. it will  pick the lv one every time you not setup the control circuit and add a form so i see no conflict here

**Comment by Dream-Master** [comment]
since control circuits not use a extra slot we can add some to lv as well. need to test if that work. so 1 for lv and 2 for hv

**Comment by Dream-Master** [comment]
image
image

**Review by chochem — APPROVED** [review]

**Pull request merged**
