### PR TITLE
Add a recipe to the Architect's Glowbrush

### PR DESCRIPTION
**Pull request by Superfrogman98**
Adds a recipe to the Glowbrush that was implemented in https://github.com/GTNewHorizons/ArchitectureCraft/pull/19

### CODE REVIEW

**Comment by IncandescenceSy** [comment]
Why is there a gear in the recipe? That seems out of place to me

**Comment by Superfrogman98** [comment]
I took the basis for the recipe from the buildcraft and extrautilities brushes which used a gear

**Comment by IncandescenceSy** [comment]
My bad, I didn't know that the BuildCraft brush already used a Gear. It still doesn't really make sense, so I would have personally used something else, but there's precedent for it being included, so there's no issue

**Review by BlueHero233 — APPROVED** [review]
looks good 
image

**Comment by Dream-Master** [comment]
Fine from my side to add the recipe since the other stuff allready in the pack.

**Pull request merged**
