### PR TITLE
Swap gated plates for adv. fluid housing

### PR DESCRIPTION
**Pull request by Lyfts**
Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14319

I agree that more fluids should be more expensive.

### CODE REVIEW

**Comment by boubou19** [comment]
show the recipes in game please

**Comment by Lyfts** [comment]
The "expensive" plates have just been swapped between them, so that the multi-fluid housing is gated later.

Adv Fluid:
advf
advf2

Adv multi fluid:

advmf
advmf2

**Comment by Dream-Master** [comment]
> The "expensive" plates have just been swapped between them, so that the multi-fluid housing is gated later.
> 
> Adv Fluid: advf advf2
> 
> Adv multi fluid:
> 
> advmf advmf2

Idk this texture pack. Vanilla please

**Comment by Lyfts** [comment]
Forgot i had texturepack.

Adv fluid housing
Before:
advfb
After:
advfn
New bottom plate is stainless steel, so that it didn't have 3 neut plates.

Adv multi fluid:
Before:
advmfb
After:
advmfn

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
