### PR TITLE
Add recipe for Fluid Void Cell

### PR DESCRIPTION
**Pull request by lordIcocain**
for https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/234

image

image

### CODE REVIEW

**Review by TheEpicGamer274 — APPROVED** [review]
Looks fine to me

**Comment by Alexdoru** [comment]
what does the item trash cell recipe look lke ?
did you make a recipe that's similar ?

**Review by Alexdoru — CHANGES_REQUESTED** [review]
don't merge, this is for an item that doesn't exist yet...

**Comment by TheEpicGamer274** [comment]
> what does the item trash cell recipe look lke ? did you make a recipe that's similar ?

its very similar, minor differences in cost, can get it in the same tier

**Comment by lordIcocain** [comment]
@Alexdoru I used as base Multi-Fluid Storage housing and add regular singularity.
item void recipe:
image

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
