### PR TITLE
Color upgrade recipe change

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**
Replacing vanilla dyes with dyes from GregTech

A long time ago when setting up the autocraft of things from Nuclear Control noticed that the color module has a recipe with vanilla dyes. I found its recipe in the code and wanted to change it to use a similar color from other mods, but did not find how to do it, so I specified the use of dyes from GregTech. Is it possible to specify the use of dyes from any mod?

### CODE REVIEW

**Comment by Dream-Master** [comment]
atm it choose all dyes not onla gt dyes. limit it to gt dyes i would not approve

**Comment by Dream-Master** [comment]
image
image
image
image
that is how it looks like now. seems it use ore dict

**Comment by Eldrinn-Elantey** [comment]
I'm talking about the recipe in the assembly machine

**Comment by Eldrinn-Elantey** [comment]
image

**Comment by Dream-Master** [comment]
ah ok. can this use all oredict items as well?

**Comment by Eldrinn-Elantey** [comment]
I wanted to do exactly through the dictionary, but I have not found an example in the code how to do it. Please tell me how to specify the dictionary and I will fix it.

**Comment by Eldrinn-Elantey** [comment]
I found this example in the code. But having checked it in the game it also accepted only vanilla red dye.
```
GTValues.RA.stdBuilder()
                    .itemInputs(
                            GTOreDictUnificator.get(OrePrefixes.dust, Materials.Sugar, 1L),
                            GTOreDictUnificator.get(OrePrefixes.cell, Materials.Fuel, 1L),
                            GTOreDictUnificator.get(OrePrefixes.cell, Materials.SulfuricAcid, 1L),
                            GTOreDictUnificator.get(OrePrefixes.cell, Materials.Acetone, 1L),
                            GTModHandler.getModItem(PamsHarvestCraft.ID, "pepperoniItem", 1L, 0),
                            GTOreDictUnificator.get(OrePrefixes.dye, Materials.Red, 1L),
                            GTUtility.getIntegratedCircuit(1))
                    .itemOutputs(GTModHandler.getModItem(OpenComputers.ID, "item", 1L, 18))
                    .fluidInputs(FluidRegistry.getFluidStack("mead", 1000)).duration(10 * MINUTES).eut(TierEU.RECIPE_HV)
                    .addTo(assemblerRecipes);
```

**Comment by FourIsTheNumber** [comment]
> I wanted to do exactly through the dictionary, but I have not found an example in the code how to do it. Please tell me how to specify the dictionary and I will fix it.

Not possible, assembler recipe with gt dyes should be correct

**Comment by Dream-Master** [comment]
image
show only vanilla item

but maybe we can implement it to use all colors . would be great

**Comment by Eldrinn-Elantey** [comment]
> > I wanted to do exactly through the dictionary, but I have not found an example in the code how to do it. Please tell me how to specify the dictionary and I will fix it.
> 
> Not possible, assembler recipe with gt dyes should be correct

Now a recipe with vanilla dye

**Comment by Dream-Master** [comment]
go ahead use gt dyes until we find a solution use all dyes

**Comment by FourIsTheNumber** [comment]
Currently no support for proper oredict in machines, this can’t be done with the existing system for gt recipes. For now default should be using the gt dyes and if someone wants to rewrite how recipes work it can be changed

**Comment by Eldrinn-Elantey** [comment]
When I was looking for an example of specifying all colors, I noticed that for example for Steve's Carts components that are made in the assembler separate recipes for dyes from different mods

**Comment by Eldrinn-Elantey** [comment]
Shall we change the vanilla dyes in the recipe to dyes from GT now, or wait for a way to develop a way to specify dyes from any mods?

**Comment by Dream-Master** [comment]
> Shall we change the vanilla dyes in the recipe to dyes from GT now, or wait for a way to develop a way to specify dyes from any mods?

yes us gt ones

**Comment by Eldrinn-Elantey** [comment]
If I have correctly specified the use of GT colorants in the recipe, it can be merged
```
GTValues.RA.stdBuilder() // Color upgrade
                .itemInputs(
                        ItemList.Color_01.get(1L),
                        ItemList.Color_02.get(1L),
                        ItemList.Color_04.get(1L),
                        GTOreDictUnificator.get(OrePrefixes.circuit, Materials.HV, 1L))
                .itemOutputs(getModItem(IC2NuclearControl.ID, "ItemUpgrade", 1, 1, missing)).duration(20 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(assemblerRecipes);
```

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
