### PR TITLE
add ae2fc cells recipe

### PR DESCRIPTION
**Pull request by asdflj**
add ae2fc cells recipe

ADVANCED FLUID STORAGE HOUSING
image

AE2FC MULTI FLUID STORAGE HOUSING
image

ADVANCED MULTI FLUID STORAGE HOUSING
image

Quantum Storage Cell
image

Digital Singularity Cell
image

### CODE REVIEW

**Comment by chochem** [comment]
well this for after stable anyway, its a clear feature addition.

@asdflj you really have to write longer PR descriptions. This is not ok. Maybe pics of the quantum/singularity recipes. And certainly a list of what is being added.

Regarding singularity/lewis: maybe add yotta parts to the singularity recipe? not sure which one would be appropriate.

**Review by chochem — CHANGES_REQUESTED** [review]
do not merge. we have a feature freeze. also the quantum cell has the wrong type amount currently. (same mistake as for the item one previously)

**Comment by chochem** [comment]
recipe? well read what lewis wrote above.

That is not the main problem though. the quantum storage cell is bugged. (and its a feature addition during feature freeze!)

**Comment by EnderProyects** [comment]
> yottanks Just let him change the recipe so its require advanced yottanks multi parts in the recipe

**Comment by chochem** [comment]
maybe just remove quantum and singularity from the PR for now?

**Comment by Dream-Master** [comment]
if the other recipes are ok @chochem maybe a good way to integrated it in rc5

**Comment by Dream-Master** [comment]
i just comment them out for now

**Review by chochem — APPROVED** [review]

**Pull request merged**
