### PR TITLE
Fix good circuit recipe

### PR DESCRIPTION
**Pull request by HoleFish**
The ingredient circuit was accidentally oredicted during cleanup

### CODE REVIEW

**Comment by Dream-Master** [comment]
Why this should be not oredicted ?

**Comment by FourIsTheNumber** [comment]
> Why this should be not oredicted ?

It's part of a circuit line and should only use the specific preceding circuit, not any LV. the output is an MV circuit.

**Comment by chochem** [comment]
There is no bug in any refactor. The ic2 circuit was the unification in the past before I switched it to the lv-any.
So -for technical reasons- this was always oredicted.

**Comment by Dream-Master** [comment]
@chochem if it should be ordicted the pr can be deleted ?

**Comment by chochem** [comment]
I am happy with it. brings it in line with the other circuit lines. unless you dont want it of course.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
