### PR TITLE
Remove old hatch recipes

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4977 and https://github.com/Technus/TecTech/pull/53.

### CODE REVIEW

**Comment by Dream-Master** [comment]
For me ok so far it is pulled in Tec tech

**Review by Dream-Master — APPROVED** [review]

**Comment by Prometheus0000** [comment]
The PR to add the new recipes hasn't been merged in the TT repo yet though?

**Comment by Dream-Master** [comment]
@Prometheus0000 merged in my forked repo until @Technus look at it. I update jenkins to gtnh repo

**Comment by Prometheus0000** [comment]
I didn't see we had one or that you forked one. I was thinking it might be a good idea given that bass left and both him and technus aren't particularly active.

**Comment by Dream-Master** [comment]
@Prometheus0000 https://github.com/GTNewHorizons/TecTech
https://github.com/GTNewHorizons/TecTech/commit/7dc702d9dcfb2b0fa649f1480b976bb6cbde67d2
https://github.com/GTNewHorizons/TecTech/commit/d96e2dcde70dbdd4c1a7a4237c6ac11c51c2003e

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8080/job/Tec%20Tech/646/

**Pull request merged**
