### PR TITLE
Localization improve

### PR DESCRIPTION
**Pull request by Antifluxfield**
Following https://github.com/GTNewHorizons/GT5-Unofficial/pull/45.
Besides, there's already a constructor to customize the tick time of Item Pipes, but why are you still using your own class, even they are almost the same... Thus I delete the redundant one here.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Antifluxfield I see you remove the GT_CustomMetaPipeEntity_Item.java file. Did the Tin pipes that have a trasfer rate below 1 item each tick working as they should? small tin pipes pumping all 20 or all 40 tick one block.

**Comment by Antifluxfield** [comment]
Nope... But that's a hidden bug of GT itself :joy:
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/48

**Comment by Dream-Master** [comment]
Ok good

**Comment by Dream-Master** [comment]
@Antifluxfield thanks

**Pull request merged**
