### PR TITLE
HazardousItems unlikely arg type

### PR DESCRIPTION
**Pull request by bartimaeusnek**

### CODE REVIEW

**Comment by Dream-Master** [comment]
what it fix? @bartimaeusnek

**Comment by Namikon** [comment]
Are you sure this is working? HazardousItems wasn't broken.
ItemDescriptor overrides toString() and returns [modID]:[itemID]:[metaID].
Does getItemName do the same?

**Comment by Dream-Master** [comment]
@bartimaeusnek @Namikon so we need to revert it?

**Comment by bartimaeusnek** [comment]
@Dream-Master it has already been reverted

**Comment by Dream-Master** [comment]
k

**Pull request merged**
