### PR TITLE
Part of the other PR

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT5-Unofficial/pull/368

### CODE REVIEW

**Comment by Dream-Master** [comment]
Not needed anymore i guess. @Prometheus0000 @bartimaeusnek

**Comment by Prometheus0000** [comment]
Bart still hasn't responded to my questions as to why he closed the other part of the PR.

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by bartimaeusnek** [comment]
@Prometheus0000 cause its not working with the new changes i made to the codebase, also people seemed to agree that the infinity alloy coils shouldve been replaced, so i closed it.

**Comment by Prometheus0000** [comment]
> people seemed to agree that the infinity alloy coils shouldve been replaced

Replaced with what? You didn't add a coil post-Dr* did you? I didn't see it? Also, what people said it should be replaced? I think bot and some said _made more complex_, is that what you mean?

**Comment by bartimaeusnek** [comment]
> Replaced with what? You didn't add a coil post-Dr* did you? I didn't see it?

I didn't add a new coil post Dr*. 

>  Also, what people said it should be replaced? I think bot and some said _made more complex_, is that what you mean?

yes

**Comment by Prometheus0000** [comment]
I'll work on it again once I have some time to rejigger it.

**Pull request closed without merging**
